In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# taking a array
x = np.array([[2, 2, 3], 
              [1, 5, 6], 
              [7, 8, 9]])

# function for making [0,0] = 1
def pivot_00(x):
    if x[0,0] == 1:
        return 

    elif x[:,0] == 1:
        x[: ,0] = x[0,:]
    
    else:
        return
    
pivot_00(x)

In [ ]:
identity_mat = np.array([[1,0,0],
                        [0,1,0],
                        [0,0,1]])

new_array = np.hstack((x, identity_mat))
print(f"New array: {new_array}")

[1 4 7]
[1 2 3]


In [ ]:
def calculate(new_array):

    # dynamically attributable with [0,0] to make x[1:,0] = 0

    element_00 = -[1,0]
    row = new_array[0,:]*element_00

    row1 = new_array[1,:] - row

    element_00 = [-2,0]

array([2, 2, 3])