In [ ]:
import numpy as np

# taking a array
x = np.array([[2, 2, 3], 
              [1, 5, 6], 
              [7, 8, 9]])

# ----------------------------------------------------
# function for making [0,0] = 1
def pivot_00(x):

    if x[0,0] == 1:
        return x

    elif 1 in x[:,0]:
        row_index = np.where(x[:,0] == 1)[0][0]
        x[[0, row_index]] = x[[row_index, 0]]
        return x

    else:
        return x
print(f"New Pivot: {pivot_00(x)}")

# ---------------------------------------------------
# attaching identity matrix for roots
identity_mat = np.array([[1,0,0],
                        [0,1,0],
                        [0,0,1]])

new_array = np.hstack((x, identity_mat))
print(f"New array: {new_array}")

#-----------------------------------------------------
def first_reduction(new_array):

    # eliminate row 1
    element_00 = -new_array[1,0]
    row = new_array[0,:] * element_00
    row1 = new_array[1,:] + row

    # eliminate row 2
    element_00 = -new_array[2,0]
    row = new_array[0,:] * element_00
    row2 = new_array[2,:] + row

    # update matrix
    new_array[1,:] = row1
    new_array[2,:] = row2

    return new_array

print(f"1st reduction: {first_reduction(new_array)}")


def second_reduction(new_array):

    element_11 = 


New Pivot: [[1 5 6]
 [2 2 3]
 [7 8 9]]
New array: [[1 5 6 1 0 0]
 [2 2 3 0 1 0]
 [7 8 9 0 0 1]]
1st reduction: [[  1   5   6   1   0   0]
 [  0  -8  -9  -2   1   0]
 [  0 -27 -33  -7   0   1]]


In [ ]:
# instead of brute forcing make these function first.

swap_rows()
scale_row()
eliminate_row()
find_pivot()