In [1]:
import numpy as np

arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
arr[-3:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [2]:
print(arr[2,:])
print(arr[:,1])
print(arr[-2:, -2:])

[11 12 13 14 15]
[ 2  7 12 17 22]
[[19 20]
 [24 25]]


In [3]:
print(arr[-2:, -2:])
print(arr[arr % 2 ==0])

[[19 20]
 [24 25]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]
