build mortgage calculator
# 8:05 pm

## 5. Random arrays

Create a 10×10 array of random numbers.

Find:
1. Maximum value and its position.
1. Minimum value and its position.
1. Mean, median, and standard deviation.


In [1]:
import numpy as np

arr = np.random.randint(0, 100, (10, 10))
print(arr)

[[38 13 77 22 47 52 30 83  5  2]
 [40 96 51 33 58 18 95 26 46 57]
 [ 8  6 32 32 92 60 97 32 81 32]
 [34 26 72  2 22 63 27 70 37 19]
 [76  8 68 63  4  4 55 60 45  9]
 [90 80 13 98 70  5 58 19  5  0]
 [44 89 73  4 36  3 62 33 52 86]
 [21 80 12 30 30 14 72 19 17 66]
 [32  0 24 55 47 29 26 53 93 74]
 [92 96 75 71 60 44 38 10 93 79]]


In [3]:
print(arr.max())
print(arr.argmax())

98
53


In [5]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

44.97
42.0
29.207004296914807


In [18]:
import numpy as np

arr = np.random.randint(0,101, size=50)
print(arr)

print()
print(arr.max(),arr.min())

[45 90 88 92 45 49 84 40 81 37 89 26  2 93  9 35  0 25 98  9  4 17 45 47
 37 45 13  3 34 39 70 18 74 59 78 27 20 70 57 45  6 57 73 70 96 38  3 50
 79 42]

98 0


## 6. Boolean masking 
Given:

1. arr = np.random.randint(1, 100, 30)
2. Extract all numbers greater than 50.
2. Replace all numbers less than 25 with 0.
2. Count how many numbers are divisible by 3.

In [9]:
import numpy as np

arr = np.random.randint(1, 100, 30)
print(arr)

# 1. Extract all numbers greater than 50
greater_than_50 = arr[arr > 50]
print(greater_than_50)

# 2. Replace all numbers less than 25 with 0
arr[arr < 25] = 0
print(arr)

# 3. Count numbers divisible by 3
count = np.sum(arr % 3 == 0)
print(count)

[72 97 41 18 57 25 67 63 10 24 88 31 89 60 67 63 31 84 97 61 84 54 29 36
 82 28 81  3 32 88]
[72 97 57 67 63 88 89 60 67 63 84 97 61 84 54 82 81 88]
[72 97 41  0 57 25 67 63  0  0 88 31 89 60 67 63 31 84 97 61 84 54 29 36
 82 28 81  0 32 88]
14


In [2]:
import numpy as np
arr = np.random.randint(1,21, size=20)
print(arr)


arr = np.sort(arr)
print(arr[-5:])

[ 2 19 10  1  4  4 16 20 13 16  8  4 16  6  1  9  8 11  6  8]


In [11]:
import numpy as np

arr = np.random.randint(1, 21, size=20)
print("Original:", arr)

# Sort ascending
arr_sorted = np.sort(arr)
print("Ascending:", arr_sorted)

# Sort descending
arr_desc = arr_sorted[::-1]
print("Descending:", arr_desc)

# Top 5 largest elements
print("Top 5:", arr_desc[:5])

Original: [14  4  9 13 15  4 13 18 17 10 13 18 19 19 16 12  7 14 18 19]
Ascending: [ 4  4  7  9 10 12 13 13 13 14 14 15 16 17 18 18 18 19 19 19]
Descending: [19 19 19 18 18 18 17 16 15 14 14 13 13 13 12 10  9  7  4  4]
Top 5: [19 19 19 18 18]


In [13]:
top5 = arr_sorted[-5:][::-1]
print(top5)

[19 19 19 18 18]
