In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# 1. Add a vector to a matrix
A = np.arange(9).reshape(3,3)
a = np.array([100,200,300])

print("A:\n", A)
print("a:", a)
print("A + a:\n", A + a)

A:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
a: [100 200 300]
A + a:
 [[100 201 302]
 [103 204 305]
 [106 207 308]]


In [ ]:
# 2. Add a column vector to a matrix
B = np.arange(9).reshape(3,3)
b = np.array([[10],[20],[30]])

print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print("B:\n", B)
print("b:\n", b)
print("B + b:\n", B + b)

B:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b:
 [[10]
 [20]
 [30]]
B + b:
 [[10 11 12]
 [23 24 25]
 [36 37 38]]


In [ ]:
# 3. Multiply a matrix by a 1-D array
C = np.random.randint(1,5,size=(4,4))
c = np.array([1,10,100,1000])

print("C * c:\n", C * c)

C * c:
 [[   4   40  300 4000]
 [   4   10  200 3000]
 [   2   10  200 4000]
 [   1   10  200 2000]]


In [20]:
# 4. Add a scalar
D = np.random.randint(-5,5, size=(3,5))
print(D + 7)

[[ 3  9  6  4  9]
 [ 4  6  9  3  2]
 [ 6  3  7 10  6]]


In [1]:
# 5. Add two shapes that should fail (see the error)
X = np.ones((3,4))
Y = np.ones((2,3))
X + Y

NameError: name 'np' is not defined

In [22]:
# 6. Broadcast a 1×3 row across a 3×3 matrix
A = np.arange(9).reshape(3,3)
v = np.array([[10,20,30]])

print(A + v)

[[10 21 32]
 [13 24 35]
 [16 27 38]]


In [23]:
# 7. Broadcast a 3×1 column across a 3×3 matrix
A = np.arange(9).reshape(3,3)
v = np.array([[10],[20],[30]])

print(A + v)

[[10 11 12]
 [23 24 25]
 [36 37 38]]


In [24]:
# 8. Multiply 1-D array by 2-D matrix
A = np.arange(12).reshape(4,3)
w = np.array([100,200,300])

print(A * w)

[[   0  200  600]
 [ 300  800 1500]
 [ 600 1400 2400]
 [ 900 2000 3300]]


In [25]:
# 9. Try a crazy shape pairing and see what breaks
X = np.random.randn(2,3,4)
Y = np.random.randn(4)

print(X + Y)

[[[-1.68932242 -0.69786224  0.42238186 -0.37541828]
  [-1.39963711  2.59813029 -0.29649543 -1.65330139]
  [-0.84645844  4.09952783  0.24345172 -0.77400669]]

 [[-2.04227276  0.19250087 -0.50482858  0.3846147 ]
  [-1.82280538  1.93462408 -0.62868154 -2.21687977]
  [-2.68543049  1.73363949  0.75756393 -0.57100909]]]


In [26]:
Z = np.random.randn(3)
print(X + Z)

ValueError: operands could not be broadcast together with shapes (2,3,4) (3,) 

In [27]:
# 10. Outer sum experiment
x = np.arange(4)
y = np.arange(6)

print(x[:, None] + y)


[[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]]
