1. How about the project with Gaussian elimination and coding and attaching a plot of every step, of how does a particular step changes the plane, and how do changes in matrix affect the plot?

2. https://youtu.be/bnC848ie16Q?si=JKd-dx4Oy4r1Y2z1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# taking a array
x = np.array([[2, 2, 3], 
              [1, 5, 6], 
              [7, 8, 9]])

# function for making [0,0] = 1
def pivot_00(x):
    if x[0,0] == 1:
        return 

    elif x[:,0] == 1:
        x[: ,0] = x[0,:]
    
    else:
        return
    
pivot_00(x)

In [ ]:
identity_mat = np.array([[1,0,0],
                        [0,1,0],
                        [0,0,1]])

new_array = np.hstack((x, identity_mat))
print(f"New array: {new_array}")

[1 4 7]
[1 2 3]


In [ ]:
def calculate(new_array):

    # dynamically attributable with [0,0] to make x[1:,0] = 0

    element_00 = -[1,0]
    row = new_array[0,:]*element_00

    row1 = new_array[1,:] - row

    element_00 = [-2,0]

array([2, 2, 3])

In [3]:
import numpy as np
from scipy import linalg

# Define a square matrix
A = np.array([[1, 2], 
              [3, 4]])

# Compute the inverse
A_inv = linalg.inv(A)

print("Original Matrix:\n", A)
print("Inverse Matrix:\n", A_inv)

# Verify the result: A * A_inv should be an Identity Matrix
print("Verification (A * A_inv):\n", np.dot(A, A_inv))


Original Matrix:
 [[1 2]
 [3 4]]
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Verification (A * A_inv):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
