### make notes and understand basic numpy functions

### Gaussian Elimination

In [ ]:
import numpy as np
def gaussian_elimination():
    matrix = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
    
 

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
m = np.array([[10, 20, 30], 
              [40, 50, 60], 
              [70, 80, 90]])

row_1 = m[1, :]
col_2 = m[:, 2]    

print(row_1)
print(col_2)

[40 50 60]
[30 60 90]
