# 8:00

In [1]:
import numpy as np
import matplotlib.pyplot as plt
# plt.style.use(['science', 'notebook', 'dark_background'])

In [2]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(3)
y = np.arange(3)

print(x)
print(y)
print()
xv, yv = np.meshgrid(x, y)

print(xv)
print(yv)

[0 1 2]
[0 1 2]

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [3]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(2)
y = np.arange(2)

print(x)
print(y)
print()
xv, yv = np.meshgrid(x, y)

print(xv)
print(yv)

[0 1]
[0 1]

[[0 1]
 [0 1]]
[[0 0]
 [1 1]]


In [4]:
x = np.linspace(-5,5,100)
y = np.linspace(-5,5,100)

X, Y = np.meshgrid(x,y)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.array([[1], 
              [2], 
              [3]])
y = np.array([10, 20])

print(x.shape)

plt.figure(figsize=(6,2))
X, Y = np.meshgrid(x, y)
plt.scatter(X, Y)
plt.show()